version: '3.8'

services:
  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  app:
    build: .
    container_name: redis-rate-limiter
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - app-network
    volumes:
      - ./logs:/var/log/myapp # For file logging

networks:
  app-network:
    driver: bridge